 


    var jobtitles = [
        "Account Collector",
        "Accounting Clerk",
        "Administrative Assistant",
        "Administrative Coordinator",
        "Administrative Director",
        "Administrative Manager",
        "Administrative Services Manager",
        "Administrative Services Officer",
        "Administrative Specialist",
        "Administrative Support Manager",
        "Administrative Support Supervisor",
        "Administrator",
        "Assistant Director",
        "Auditing Clerk",
        "Bill Collector",
        "Billing Clerk",
        "Billing Coordinator",
        "Bookkeeper",
        "Chairman",
        "Client Relations Manager",
        "Contract Administrator",
        "Credit Clerk",
        "Data Entry",
        "Engineer",
        "Executive Assistant",
        "Executive Services Administrator",
        "Facility Manager",
        "File Clerk",
        "Financial Clerk",
        "General Manager",
        "General Office Clerk",
        "Graphic Designer",
        "Human Resources Administrator",
        "Information Clerk",
        "Legal Secretary",
        "Line Manager",
        "Mail Clerk",
        "Mail Clerk Leader",
        "Managing Director",
        "Material Recording Clerk",
        "Media Coodinator",
        "Medical Secretary",
        "Network Engineer",
        "Office Assistant",
        "Office Clerk",
        "Office Manager",
        "Office Support Manager",
        "Office Support Supervisor",
        "Program Administrator",
        "Program Manager",
        "Programmar",
        "Receptionist",
        "Records Management Analyst",
        "Sales Coodinator",
        "Sales Manager",
        "Secretary",
        "Senior Administrative Analyst",
        "Senior Administrative Coordinator",
        "Senior Administrative Services Officer",
        "Senior Coordinator",
        "Senior Executive Assistant",
        "Senior Special Events Coordinator",
        "Senior Support Assistant",
        "Senior Support Specialist",
        "Software Engineer",
        "Special Events Coordinator",
        "Special Programs Coordinator",
        "Staff Assistant",
        "Supervisor",
        "Support Assistant",
        "Support Specialist",
        "Typist",
        "Virtual Assistant",
        "Virtual Receptionist",
        "Web Developer",
        "Word Processor"
    ];

    $("#keywords,#keyword").autocomplete({
        source: jobtitles
    });

    var availableTags = [
        "Arabian Gulf University",
        "Bahrain Polytechnic",
        "College of Health Sciences",
        "University of Bahrain",
        "Private universities and higher education institutions",
        "Arab Open University",
        "AMA International University",
        "Applied Science University",
        "Ahlia University",
        "Bahrain Institute of Banking and Finance",
        "Bentley University",
        "Birla Institute of Technology International Centre",
        "British University of Bahrain",
        "Delmon University for Science & Technology",
        "DePaul University",
        "Gulf University",
        "Hull University",
        "Kent Business Foundation Courses in Bahrain",
        "The Kingdom University",
        "Royal College of Surgeons in Ireland(RCSI) - Bahrain",
        "Royal University for Women",
        "Talal Abu Ghazaleh University College of Business",
        "University College of Bahrain",
        "University of Wales, Bangor",
        "Stanford University, United States",
        "Harvard University, United States",
        "University of Oxford, United Kingdom",
        "University of Hong Kong, Hong Kong",
        "University of California, Berkeley, United States",
        "University of Wisconsin-Madison, United States",
        "University of California, Los Angeles, United States",
        "University of Michigan, United States",
        "University of Pennsylvania, United States",
        "Michigan State University, United States",
        "University of Toronto, Canada",
        "Vanderbilt University, United States",
        "University of British Columbia, Canada",
        "Columbia University, United States",
        "Johns Hopkins University, United States",
        "University College London, United Kingdom",
        "University of Cambridge, United Kingdom",
        "King’s College London, United Kingdom",
        "University of Washington, United States",
        "Chinese University of Hong Kong, Hong Kong",
        "University of Melbourne, Australia",
        "National Taiwan Normal University, Taiwan",
        "University of Southern California, United States",
        "University of Sydney, Australia",
        "Pennsylvania State University, United States",
        "Humboldt University of Berlin, Germany",
        "Nanyang Technological University, Singapore",
        "Arizona State University, United States",
        "University of Queensland, Australia",
        "University of Minnesota, United States",
        "Utrecht University, Netherlands",
        "Indiana University, United States",
        "University of Texas at Austin, United States",
        "Florida State University, United States",
        "University of Helsinki, Finland",
        "McGill University, Canada",
        "University of Auckland, New Zealand",
        "Monash University, Australia",
        "Boston College, United States",
        "University of Bristol, United Kingdom",
        "Ohio State University, United States",
        "The Open University, United Kingdom",
        "Seoul National University, South Korea",
        "University of Virginia, United States",
        "National Taiwan University of Science and Technology (Taiwan Tech), Taiwan",
        "University of North Carolina at Chapel Hill, United States",
        "University of Tokyo, Japan",
        "Brown University, United States",
        "Ghent University, Belgium",
        "University of Sheffield, United Kingdom",
        "Durham University, United Kingdom",
        "University of Edinburgh, United Kingdom",
        "University of Tübingen, Germany",
        "Lancaster University, United Kingdom",
        "University of Georgia, United States",
        "Maastricht University, Netherlands",
        "University of Amsterdam, Netherlands",
        "University of California, San Diego, United States",
        "University of Maryland, College Park, United States",
        "University of Alberta, Canada",
        "LMU Munich, Germany",
        "University of New South Wales, Australia",
        "University of Hamburg, Germany",
        "University of Southampton, United Kingdom",
        "KU Leuven, Belgium",
        "University of Colorado Boulder, United States",
        "Korea University, South Korea",
        "University of Manchester, United Kingdom",
        "University of Nottingham, United Kingdom",
        "Free University of Berlin, Germany",
        "University of Technology Sydney, Australia",
        "University of California, Santa Barbara, United States",
        "University of Pittsburgh, United States",
        "University of California, Irvine, United States",
        "Delft University of Technology, Netherlands",
        "University of Warwick, United Kingdom",
        "University of Exeter, United Kingdom",
        "Cardiff University, United Kingdom",
        "University of Western Australia, Australia",
        "University of Zurich, Switzerland",
        "Boston University, United States",
        "National Sun Yat-Sen University, Taiwan",
        "University of Oslo, Norway",
        "University of Jyväskylä, Finland",
        "Tufts University, United States",
        "University of Connecticut, United States",
        "University of Hawai’i at Mānoa, United States",
        "University of Groningen, Netherlands",
        "University of Glasgow, United Kingdom",
        "Queensland University of Technology, Australia",
        "University of Rochester, United States",
        "University of York, United Kingdom",
        "University of Kansas, United States",
        "University of Miami, United States",
        "University of Oregon, United States",
        "University of Bath, United Kingdom",
        "Lomonosov Moscow State University, Russian Federation",
        "Simon Fraser University, Canada",
        "Trinity College Dublin, Republic of Ireland",
        "Yonsei University (Seoul campus), South Korea"
    ];
 
    var unidegrees = [
        "Bachelor of Architecture",
        "Bachelor of Biomedical Science",
        "Bachelor of Business Administration",
        "Bachelor of Clinical Science",
        "Bachelor of Commerce",
        "Bachelor of Computer Applications",
        "Bachelor of Community Health",
        "Bachelor of Computer Information Systems",
        "Bachelor of Science in Construction Technology",
        "Bachelor of Criminal Justice",
        "Bachelor of Divinity",
        "Bachelor of Economics",
        "Bachelor of Education",
        "Bachelor of Engineering",
        "Bachelor of Fine Arts",
        "Bachelor of Letters",
        "Bachelor of Information Systems",
        "Bachelor of Management",
        "Bachelor of Music",
        "Bachelor of Pharmacy",
        "Bachelor of Philosophy",
        "Bachelor of Social Work",
        "Bachelor of Technology",
        "Bachelor of Accountancy",
        "Bachelor of Arts in American Studies",
        "Bachelor of Arts in American Indian Studies",
        "Bachelor of Arts in Applied Psychology",
        "Bachelor of Arts in Biology",
        "Bachelor of Arts in Anthropology",
        "Bachelor of Arts in Child Advocacy",
        "Bachelor of Arts in Clinical Psychology",
        "Bachelor of Arts in Forensic Psychology",
        "Bachelor of Arts in Organizational Psychology",
        "Bachelor of Science in Aerospace Engineering",
        "Bachelor of Science in Actuarial",
        "Bachelor of Science in Agriculture",
        "Bachelor of Science in Architecture",
        "Bachelor of Science in Architectural Engineering",
        "Bachelor of Science in Athletic Training",
        "Bachelor of Science in Biology",
        "Bachelor of Science in Biomedical Engineering",
        "Bachelor of Science in Bible",
        "Bachelor of Science in Business Administration",
        "Bachelor of Science in Business and Technology",
        "Bachelor of Science in Chemical Engineering",
        "Bachelor of Science in Chemistry",
        "Bachelor of Science in Civil Engineering",
        "Bachelor of Science in Clinical Laboratory Science",
        "Bachelor of Science in Cognitive Science",
        "Bachelor of Science in Computer Engineering",
        "Bachelor of Science in Computer Science",
        "Bachelor of Science in Construction Engineering",
        "Bachelor of Science in Construction Management",
        "Bachelor of Science in Criminal Justice",
        "Bachelor of Science in Criminology",
        "Bachelor of Science in Diagnostic Radiography",
        "Bachelor of Science in Education",
        "Bachelor of Science in Electrical Engineering",
        "Bachelor of Science in Engineering Physics",
        "Bachelor of Science in Engineering Science",
        "Bachelor of Science in Engineering Technology",
        "Bachelor of Science in English Literature",
        "Bachelor of Science in Environmental Engineering",
        "Bachelor of Science in Environmental Science",
        "Bachelor of Science in Environmental Studies",
        "Bachelor of Science in Food Science",
        "Bachelor of Science in Foreign Service",
        "Bachelor of Science in Forensic Science",
        "Bachelor of Science in Forestry",
        "Bachelor of Science in History",
        "Bachelor of Science in Hospitality Management",
        "Bachelor of Science in Human Resources Management",
        "Bachelor of Science in Industrial Engineering",
        "Bachelor of Science in Information Technology",
        "Bachelor of Science in Information Systems",
        "Bachelor of Science in Integrated Science",
        "Bachelor of Science in International Relations",
        "Bachelor of Science in Journalism",
        "Bachelor of Science in Legal Management",
        "Bachelor of Science in Management",
        "Bachelor of Science in Manufacturing Engineering",
        "Bachelor of Science in Marketing",
        "Bachelor of Science in Mathematics",
        "Bachelor of Science in Mechanical Engineering",
        "Bachelor of Science in Medical Technology",
        "Bachelor of Science in Metallurgical Engineering",
        "Bachelor of Science in Meteorology",
        "Bachelor of Science in Microbiology",
        "Bachelor of Science in Mining Engineering",
        "Bachelor of Science in Molecular Biology",
        "Bachelor of Science in Neuroscience",
        "Bachelor of Science in Nursing",
        "Bachelor of Science in Nutrition science",
        "Bachelor of Science in Software Engineering",
        "Bachelor of Science in Petroleum Engineering",
        "Bachelor of Science in Podiatry",
        "Bachelor of Science in Pharmacology",
        "Bachelor of Science in Pharmacy",
        "Bachelor of Science in Physical Therapy",
        "Bachelor of Science in Physics",
        "Bachelor of Science in Plant Science",
        "Bachelor of Science in Politics",
        "Bachelor of Science in Psychology",
        "Bachelor of Science in Public Safety",
        "Bachelor of Science in Quantity Surveying Engineering",
        "Bachelor of Science in Radiologic Technology",
        "Bachelor of Science in Real-Time Interactive Simulation",
        "Bachelor of Science in Religion",
        "Bachelor of Science in Respiratory Therapy",
        "Bachelor of Science in Risk Management and Insurance",
        "Bachelor of Science in Science Education",
        "Bachelor of Science in Sports Management",
        "Bachelor of Science in Systems Engineering",
        "Bachelor of Music in Jazz Studies",
        "Bachelor of Music in Composition",
        "Bachelor of Music in Performance",
        "Bachelor of Music in Theory",
        "Bachelor of Music in Music Education",
        "Bachelor of Science in Veterinary Technology",
        "Master degrees",
        "Master of Accountancy",
        "Master of Accounting and Information Systems",
        "Master of Advanced Study",
        "Master of Applied Finance",
        "Master of Applied Mathematical Sciences",
        "Master of Applied Psychology",
        "Master of Applied Science",
        "Master of Architecture",
        "Master of Arts",
        "Master of Arts in Archives and Records Management",
        "Master of Arts in Liberal Studies",
        "Master of Arts in Museum Studies",
        "Master of Arts in Strategic Communication Management",
        "Master of Arts in Teaching",
        "Master of Athletic Training",
        "Master of Bioinformatics",
        "Master of Biotechnology",
        "Master of Business Administration",
        "Master of Business Administration Management of Technology",
        "Master of Business",
        "Master of Business Economics",
        "Master of Business Engineering",
        "Master of Business Informatics",
        "Master of Chemistry",
        "Master of City Planning",
        "Master of Commerce",
        "Master of Community Health",
        "Master of Computational Finance",
        "Master of Computer Applications",
        "Master of Computer Science",
        "Master of Communication",
        "Master of Counseling",
        "Master of Criminal Justice",
        "Master in Creative Technologies",
        "Master of Design",
        "Master of Divinity",
        "Master of Economics",
        "Master of Education",
        "Master of Educational Technology",
        "Master of Engineering",
        "Master of Engineering Management",
        "Master of Enterprise",
        "Master of European Law",
        "Master of Finance",
        "Master of Financial Economics",
        "Master of Financial Engineering",
        "Master of Financial Mathematics",
        "Master of Fine Arts",
        "Master of Health Administration",
        "Master of Health Science",
        "Master of Humanities",
        "Master of Industrial and Labor Relations",
        "Master of International Affairs",
        "Master of International Business",
        "Master of International Economics",
        "Master of International Public Policy",
        "Master of International Studies",
        "Master of Information",
        "Master of Information Management",
        "Master of Information Systems",
        "Master of Information System Management",
        "Master of Islamic Studies",
        "Master of IT",
        "Master of Jurisprudence",
        "Master of Laws",
        "Master of Studies in Law",
        "Master of Landscape Architecture",
        "Master of Letters",
        "Master of Liberal Arts",
        "Master of Library and Information Science",
        "Master of Management",
        "Master of Mass Communication and Journalism",
        "Master of Mathematical Finance",
        "Master of Mathematics",
        "Master of Mathematics and Computer Science",
        "Master of Mathematics and Philosophy",
        "Master of Medical Science",
        "Master of Medicine",
        "Master of Military Art and Science",
        "Master of Music",
        "Master of Network and Communications Management",
        "Master of Occupational Therapy",
        "Master of Pharmacy",
        "Master of Philosophy",
        "Master of Physician Assistant Studies",
        "Master of Physics",
        "Master of Political Science",
        "Master of Professional Studies",
        "Master of Psychology",
        "Master of Public Administration",
        "Master of Public Affairs",
        "Master of Public Diplomacy",
        "Master of Public Health",
        "Master of Public Management",
        "Master of Public Policy",
        "Master of Public Relations",
        "Master of Public Service",
        "Master of Quantitative Finance",
        "Master of Rabbinic Studies",
        "Master of Real Estate Development",
        "Master of Religious Education",
        "Master of Research",
        "Master of Sacred Music",
        "Master of Sacred Theology",
        "Master of Science",
        "Master of Science in Applied Cognition and Neuroscience",
        "Master of Science in Athletic Training",
        "Master of Science in Bioinformatics",
        "Master of Science in Clinical Epidemiology",
        "Master of Science in Computing Research",
        "Master of Science in Cyber Security",
        "Master of Science in Education",
        "Master of Science in Engineering",
        "Master of Science in Development Administration",
        "Master of Science in Finance",
        "Master of Science in Governance & Organizational Sciences",
        "Master of Science in Government Contracts",
        "Master of Science in Health Informatics",
        "Master of Science in Human Resource Development",
        "Master of Science in Information Assurance",
        "Master of Science in Information Systems",
        "Master of Science in Information Technology",
        "Master of Science in Leadership",
        "Master of Science in Management",
        "Master of Science in Nursing",
        "Master of Science in Project Management",
        "Master of Science in Quality Assurance",
        "Master of Science in Risk Management",
        "Master of Science in Supply Chain Management",
        "Master of Science in Teaching",
        "Master of Science in Taxation",
        "Master of Social Science",
        "Master of Social Work",
        "Master of Statistics",
        "Master of Strategic Studies",
        "Master of Studies",
        "Master of Surgery",
        "Master of Theological Studies",
        "Master of Technology",
        "Master of Theology",
        "Master of Urban Planning",
        "Master of Veterinary Science",
        "Doctoral degrees",
        "Doctor of Audiology",
        "Doctor of Aviation ",
        "Doctor of Business Administration",
        "Doctor of Canon Law",
        "Doctor of Chiropractic",
        "Doctor of Commerce",
        "Doctor of Community Health",
        "Doctor of Dental Surgery",
        "Doctor of Divinity",
        "Doctor of Education",
        "Doctor of Engineering",
        "Doctor of Health Administration",
        "Doctor of Health Science",
        "Doctor of Juridical Science",
        "Doctor of Law; Legum Doctor",
        "Doctor of Liberal Studies",
        "Doctor of Management",
        "Doctor of Medicine",
        "Doctor of Ministry",
        "Doctor of Modern Languages",
        "Doctor of Musical Arts",
        "Doctor of Naturopathic Medicine",
        "Doctor of Optometry",
        "Doctor of Osteopathic Medicine",
        "Doctor of Pharmacy",
        "Doctor of Philosophy",
        "Doctor of Public Administration",
        "Doctor of Science",
        "Doctor of Theology",
        "Doctor of Veterinary Medicine",
        "Doctor of Radio oncology"
    ]

 
    var eduspecialities = [
        "Architecture",
        "Biomedical Science",
        "Business Administration",
        "Clinical Science",
        "Commerce",
        "Computer Applications",
        "Community Health",
        "Computer Information Systems",
        "Construction Technology",
        "Criminal Justice",
        "Divinity",
        "Economics",
        "Education",
        "Engineering",
        "Fine Arts",
        "Letters",
        "Information Systems",
        "Management",
        "Music",
        "Pharmacy",
        "Philosophy",
        "Social Work",
        "Technology",
        "Accountancy",
        "American Studies",
        "American Indian Studies",
        "Applied Psychology",
        "Biology",
        "Anthropology",
        "Child Advocacy",
        "Clinical Psychology",
        "Forensic Psychology",
        "Organizational Psychology",
        "Aerospace Engineering",
        "Actuarial",
        "Agriculture",
        "Architectural Engineering",
        "Athletic Training",
        "Biomedical Engineering",
        "Bible",
        "Business and Technology",
        "Chemical Engineering",
        "Chemistry",
        "Civil Engineering",
        "Clinical Laboratory Science",
        "Cognitive Science",
        "Computer Engineering",
        "Computer Science",
        "Construction Engineering",
        "Construction Management",
        "Criminology",
        "Diagnostic Radiography",
        "Electrical Engineering",
        "Engineering Physics",
        "Engineering Science",
        "Engineering Technology",
        "English Literature",
        "Environmental Engineering",
        "Environmental Science",
        "Environmental Studies",
        "Food Science",
        "Foreign Service",
        "Forensic Science",
        "Forestry",
        "History",
        "Hospitality Management",
        "Human Resources Management",
        "Industrial Engineering",
        "Information Technology",
        "Integrated Science",
        "International Relations",
        "Journalism",
        "Legal Management",
        "Manufacturing Engineering",
        "Marketing",
        "Mathematics",
        "Mechanical Engineering",
        "Medical Technology",
        "Metallurgical Engineering",
        "Meteorology",
        "Microbiology",
        "Mining Engineering",
        "Molecular Biology",
        "Neuroscience",
        "Nursing",
        "Nutrition science",
        "Software Engineering",
        "Petroleum Engineering",
        "Podiatry",
        "Pharmacology",
        "Physical Therapy",
        "Physics",
        "Plant Science",
        "Politics",
        "Psychology",
        "Public Safety",
        "Quantity Surveying Engineering",
        "Radiologic Technology",
        "Real-Time Interactive Simulation",
        "Religion",
        "Respiratory Therapy",
        "Risk Management and Insurance",
        "Science Education",
        "Sports Management",
        "Systems Engineering",
        "Jazz Studies",
        "Composition",
        "Performance",
        "Theory",
        "Music Education",
        "Veterinary Technology",
        "Accounting and Information Systems",
        "Advanced Study",
        "Applied Finance",
        "Applied Mathematical Sciences",
        "Applied Science",
        "Arts",
        "Archives and Records Management",
        "Liberal Studies",
        "Museum Studies",
        "Strategic Communication Management",
        "Teaching",
        "Bioinformatics",
        "Biotechnology",
        "Business Administration Management of Technology",
        "Business",
        "Business Economics",
        "Business Engineering",
        "Business Informatics",
        "City Planning",
        "Computational Finance",
        "Communication",
        "Counseling",
        "Design",
        "Educational Technology",
        "Engineering Management",
        "Enterprise",
        "European Law",
        "Finance",
        "Financial Economics",
        "Financial Engineering",
        "Financial Mathematics",
        "Health Administration",
        "Health Science",
        "Humanities",
        "Industrial and Labor Relations",
        "International Affairs",
        "International Business",
        "International Economics",
        "International Public Policy",
        "International Studies",
        "Information",
        "Information Management",
        "Information System Management",
        "Islamic Studies",
        "IT",
        "Jurisprudence",
        "Laws",
        "Studies in Law",
        "Landscape Architecture",
        "Liberal Arts",
        "Library and Information Science",
        "Mass Communication and Journalism",
        "Mathematical Finance",
        "Mathematics and Computer Science",
        "Mathematics and Philosophy",
        "Medical Science",
        "Medicine",
        "Military Art and Science",
        "Network and Communications Management",
        "Occupational Therapy",
        "Physician Assistant Studies",
        "Political Science",
        "Professional Studies",
        "Public Administration",
        "Public Affairs",
        "Public Diplomacy",
        "Public Health",
        "Public Management",
        "Public Policy",
        "Public Relations",
        "Public Service",
        "Quantitative Finance",
        "Rabbinic Studies",
        "Real Estate Development",
        "Religious Education",
        "Research",
        "Sacred Music",
        "Sacred Theology",
        "Science",
        "Applied Cognition and Neuroscience",
        "Clinical Epidemiology",
        "Computing Research",
        "Cyber Security",
        "Development Administration",
        "Governance & Organizational Sciences",
        "Government Contracts",
        "Health Informatics",
        "Human Resource Development",
        "Information Assurance",
        "Leadership",
        "Project Management",
        "Quality Assurance",
        "Risk Management",
        "Supply Chain Management",
        "Taxation",
        "Social Science",
        "Statistics",
        "Strategic Studies",
        "Studies",
        "Surgery",
        "Theological Studies",
        "Theology",
        "Urban Planning",
        "Veterinary Science",
        "Audiology",
        "Aviation",
        "Canon Law",
        "Chiropractic",
        "Dental Surgery",
        "Juridical Science",
        "Law; Legum Doctor",
        "Ministry",
        "Modern Languages",
        "Musical Arts",
        "Naturopathic Medicine",
        "Optometry",
        "Osteopathic Medicine",
        "Veterinary Medicine",
        "Radio oncology",
    ]
 
    

    var skillsets = [
        "Active Directory ",
        "Adobe In Design",
        "Aluminium technician",
        "Analysis",
        "Apple (Mac)OS",
        "Application Development",
        "Arc Welding",
        "ASP.NET MVC 4",
        "AutoCAD drawing",
        "Bank Cheque",
        "Banking and finance",
        "Bookkeeping",
        "Busines Planning",
        "C#, .ASP.Net, Ajax",
        "Cash register ",
        "Communication and Wrinting Skills",
        "Communication skills",
        "Complains Handling",
        "Computer typing skills",
        "Customer service",
        "Customer Service",
        "DAD",
        "Data entry ",
        "Dealing With Children Teenager's As A Social Worke",
        "Develop",
        "Driving Skills                          -",
        "E.R.P ",
        "Email marketing",
        "Financial understanding",
        "Front office Operation",
        "Gas welding  ",
        "Group Policy",
        "Handling difficult people",
        "IT Projects",
        "IT strategic and Planning",
        "KPI calculation",
        "Master CAM",
        "Merchandise and customer service ",
        "Microsoft Excel",
        "Microsoft Office, ",
        "Microsoft Word, Microsoft PowerPoint, Microsoft Ex",
        "MS Publisher and Power",
        "Operations Management",
        "Organizing skills. ",
        "Powerpoint",
        "Radiographic Test",
        "Sales",
        "SAP Software",
        "Secretary/admin/HR",
        "Self-Management ",
        "SharePoint",
        "Site Supervisor",
        "SolidCAM",
        "SolidWorks Designer",
        "Storage Administration",
        "TALLY ",
        "Team Work",
        "Tele marketing",
        "Telephone skills",
        "Transport",
        "Underwriting",
        "Vray Rendering",
        "Web design",
        "Web developing:PHP,ASP,NET,HTML ",
        "Web programming ( HTML)",
        "Windows Server",
        "Windows Servers",
        "Work confidently within a group"
    ];
 

    var corplevels = [
        "Staff Member",
        "Coordinator",
        "Manager",
        "General Manager",
        "Chief Executive Officer",
        "Chief Operating Officer",
        "Chief Financial Officer",
        "Director",
        "Chairman"
    ];
 

    var languages = [
        "Mandarin",
        "Spanish",
        "English",
        "Hindi",
        "Arabic",
        "Portuguese",
        "Bangla",
        "Russian",
        "Japanese",
        "Punjabi",
        "German",
        "Javanese",
        "Wu",
        "Malay",
        "Telugu",
        "Vietnamese",
        "Korean",
        "French",
        "Marathi",
        "Tamil",
        "Urdu",
        "Turkish",
        "Italian",
        "Yue",
        "Thai",
        "Gujarati",
        "Jin",
        "Southern Min",
        "Persian",
        "Polish",
        "Pashto",
        "Kannada",
        "Xiang",
        "Malayalam",
        "Sundanese",
        "Hausa",
        "Odia",
        "Burmese",
        "Hakka",
        "Ukrainian",
        "Bhojpuri",
        "Tagalog",
        "Yoruba",
        "Maithili",
        "Uzbek",
        "Sindhi",
        "Amharic",
        "Fula",
        "Romanian",
        "Oromo",
        "Igbo",
        "Azerbaijani",
        "Awadhi",
        "Gan Chinese",
        "Cebuano ",
        "Dutch",
        "Kurdish",
        "Serbo-Croatian",
        "Malagasy",
        "Saraiki",
        "Nepali",
        "Sinhalese",
        "Chittagonian",
        "Zhuang",
        "Khmer",
        "Turkmen",
        "Assamese",
        "Madurese",
        "Somali",
        "Marwari",
        "Magahi",
        "Haryanvi",
        "Hungarian",
        "Chhattisgarhi",
        "Greek",
        "Chewa",
        "Deccan",
        "Akan",
        "Kazakh",
        "Northern Min ",
        "Sylheti",
        "Zulu",
        "Czech",
        "Kinyarwanda",
        "Dhundhari",
        "Haitian Creole",
        "Eastern Min ",
        "Ilocano",
        "Quechua",
        "Kirundi",
        "Swedish",
        "Hmong",
        "Shona",
        "Uyghur",
        "Hiligaynon ",
        "Mossi",
        "Xhosa",
        "Belarusian",
        "Balochi",
        "Konkani"
    ];
 
 


 

    
 