//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int app_Id { get; set; }
        public System.Guid app_GUID { get; set; }
        public System.DateTime app_Created { get; set; }
        public System.DateTime app_LastUpdated { get; set; }
        public Nullable<System.DateTime> app_Deleted { get; set; }
        public int app_vc_VacancyId { get; set; }
        public int app_ca_CandidateId { get; set; }
        public int app_st_ShortlistStatusId { get; set; }
        public int app_lm_Ranking { get; set; }
        public bool app_MayViewCV { get; set; }
        public bool app_AutoRejected { get; set; }
        public bool app_HideFromCandidate { get; set; }
        public Nullable<bool> app_ThirdPartyApply { get; set; }
        public string app_IPAddress { get; set; }
        public Nullable<int> app_CV_DocumentId { get; set; }
        public Nullable<int> app_Cover_DocumentId { get; set; }
    }
}
