//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeData
    {
        public int attd_Id { get; set; }
        public System.Guid attd_Guid { get; set; }
        public System.DateTime attd_Created { get; set; }
        public System.DateTime attd_LastUpdated { get; set; }
        public int attd_atl_AttributeListID { get; set; }
        public string attd_Value { get; set; }
        public string attd_Group { get; set; }
        public int attd_Ordinal { get; set; }
    }
}
