//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attribute()
        {
            this.AttributeResponses0 = new HashSet<AttributeResponses0>();
            this.AttributeResponses1 = new HashSet<AttributeResponses1>();
            this.AttributeResponses2 = new HashSet<AttributeResponses2>();
            this.AttributeResponses3 = new HashSet<AttributeResponses3>();
            this.AttributeResponses4 = new HashSet<AttributeResponses4>();
            this.AttributeResponses5 = new HashSet<AttributeResponses5>();
            this.AttributeResponses6 = new HashSet<AttributeResponses6>();
            this.AttributeResponses7 = new HashSet<AttributeResponses7>();
            this.AttributeResponses8 = new HashSet<AttributeResponses8>();
            this.AttributeResponses9 = new HashSet<AttributeResponses9>();
        }
    
        public int att_Id { get; set; }
        public System.Guid att_Guid { get; set; }
        public System.DateTime att_Created { get; set; }
        public int att_br_BrandId { get; set; }
        public string att_Description { get; set; }
        public int att_attt_AttributeType { get; set; }
        public Nullable<int> att_atl_AttributeListId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeResponses0> AttributeResponses0 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeResponses1> AttributeResponses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeResponses2> AttributeResponses2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeResponses3> AttributeResponses3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeResponses4> AttributeResponses4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeResponses5> AttributeResponses5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeResponses6> AttributeResponses6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeResponses7> AttributeResponses7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeResponses8> AttributeResponses8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeResponses9> AttributeResponses9 { get; set; }
        public virtual AttributeType AttributeType { get; set; }
    }
}
