//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeResponses3
    {
        public int attr_Id { get; set; }
        public System.Guid attr_Guid { get; set; }
        public System.DateTime attr_Created { get; set; }
        public System.DateTime attr_LastUpdated { get; set; }
        public int attr_att_AttributeId { get; set; }
        public int attr_ent_EntityId { get; set; }
        public int attr_RecordId { get; set; }
        public string attr_TextValue { get; set; }
        public int attr_attd_Value { get; set; }
    
        public virtual Attribute Attribute { get; set; }
    }
}
