//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditActionType
    {
        public int aat_Id { get; set; }
        public System.Guid aat_Guid { get; set; }
        public System.DateTime aat_Created { get; set; }
        public string aat_Name { get; set; }
    }
}
