//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerType
    {
        public int bt_id { get; set; }
        public System.Guid bt_GUID { get; set; }
        public System.DateTime bt_Created { get; set; }
        public string bt_Name { get; set; }
        public bool bt_HasImage { get; set; }
        public int bt_ImageMaxWidth { get; set; }
        public int bt_ImageMaxHeight { get; set; }
        public bool bt_HasTitle { get; set; }
        public bool bt_HasSummary { get; set; }
        public bool bt_HasURL { get; set; }
        public bool bt_HasWeighting { get; set; }
        public bool bt_IsWebsite { get; set; }
    }
}
