//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerBrandType
    {
        public int bbt_Id { get; set; }
        public System.Guid bbt_GUID { get; set; }
        public System.DateTime bbt_Created { get; set; }
        public int bbt_bt_BannerTypeid { get; set; }
        public int bbt_br_BrandId { get; set; }
    }
}
