//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int ban_Id { get; set; }
        public System.Guid ban_GUID { get; set; }
        public System.DateTime ban_Created { get; set; }
        public System.DateTime ban_LastUpdated { get; set; }
        public string ban_Name { get; set; }
        public int ban_us_UserId { get; set; }
        public int ban_br_BrandId { get; set; }
        public int ban_bt_BannerTypeId { get; set; }
        public int ban_cont_CommonId { get; set; }
        public bool ban_HasImage { get; set; }
        public string ban_Title { get; set; }
        public string ban_Summary { get; set; }
        public string ban_URL { get; set; }
        public int ban_Weighting { get; set; }
        public Nullable<System.DateTime> ban_Deleted { get; set; }
    }
}
