//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerPage
    {
        public int bp_ID { get; set; }
        public System.DateTime bp_created { get; set; }
        public int bp_ban_bannerid { get; set; }
        public int bp_cont_PageCommonID { get; set; }
    }
}
