//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingRequest
    {
        public int bkr_Id { get; set; }
        public System.Guid bkr_Guid { get; set; }
        public System.DateTime bkr_Created { get; set; }
        public System.DateTime bkr_LastUpdated { get; set; }
        public int bkr_ct_ContactId { get; set; }
        public int bkr_co_CompanyId { get; set; }
        public int bkr_ca_CandidateId { get; set; }
        public string bkr_StartDate { get; set; }
        public string bkr_Location { get; set; }
        public string bkr_Task { get; set; }
        public string bkr_Duration { get; set; }
        public bool bkr_Extendable { get; set; }
    }
}
