//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandCollaboration
    {
        public int brc_Id { get; set; }
        public System.Guid brc_Guid { get; set; }
        public System.DateTime brc_Created { get; set; }
        public System.DateTime brc_LastUpdated { get; set; }
        public int brc_colt_CollaborationTypeId { get; set; }
        public int brc_br_CollaboratorId { get; set; }
        public int brc_br_CollaboratingWithId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Brand Brand1 { get; set; }
        public virtual Brand Brand2 { get; set; }
        public virtual CollaborationType CollaborationType { get; set; }
    }
}
