//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brand()
        {
            this.BrandCollaborations = new HashSet<BrandCollaboration>();
            this.BrandCollaborations1 = new HashSet<BrandCollaboration>();
            this.BrandCollaborations2 = new HashSet<BrandCollaboration>();
        }
    
        public int br_Id { get; set; }
        public System.Guid br_Guid { get; set; }
        public System.DateTime br_Created { get; set; }
        public System.DateTime br_LastUpdated { get; set; }
        public Nullable<System.DateTime> br_Deleted { get; set; }
        public string br_Name { get; set; }
        public string br_SecurityKey { get; set; }
        public string br_PrimaryWebAddress { get; set; }
        public bool br_HasLogo { get; set; }
        public string br_LogoExtension { get; set; }
        public string br_Summary { get; set; }
        public int br_st_StatusId { get; set; }
        public Nullable<int> br_IntegrationKey { get; set; }
        public string br_EmailsIncoming { get; set; }
        public string br_EmailsOutgoing { get; set; }
        public string br_CultureCode { get; set; }
        public int br_br_MasterBrandId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrandCollaboration> BrandCollaborations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrandCollaboration> BrandCollaborations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrandCollaboration> BrandCollaborations2 { get; set; }
    }
}
