//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateInBox
    {
        public int in_Id { get; set; }
        public System.Guid in_GUID { get; set; }
        public System.DateTime in_Created { get; set; }
        public System.DateTime in_LastUpdated { get; set; }
        public Nullable<System.DateTime> in_Deleted { get; set; }
        public int in_co_CompanyId { get; set; }
        public int in_ct_ContactId { get; set; }
        public int in_ca_CandidateId { get; set; }
        public int in_css_ShortlistId { get; set; }
        public string in_Subject { get; set; }
        public string in_Message { get; set; }
        public Nullable<System.DateTime> in_Responded { get; set; }
        public int in_ResponseGiven { get; set; }
    }
}
