//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateSkill_T
    {
        public int CaSkill_ID { get; set; }
        public Nullable<int> Ca_ID { get; set; }
        public Nullable<int> SkillID { get; set; }
        public Nullable<int> SkillLevelID { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
    }
}
