//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateCertification
    {
        public int CaCert_ID { get; set; }
        public Nullable<int> Ca_Id { get; set; }
        public string Certification { get; set; }
        public string Authority { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public Nullable<bool> Doesnotexpire { get; set; }
    }
}
