//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateWorkHistory_Tbkp11nov2018
    {
        public int CaWorkHistory_ID { get; set; }
        public Nullable<int> Ca_ID { get; set; }
        public Nullable<int> JobTitleID { get; set; }
        public string Company { get; set; }
        public Nullable<int> JobLevelID { get; set; }
        public Nullable<int> ReportingToID { get; set; }
        public Nullable<int> IndustryID { get; set; }
        public Nullable<int> FunctionID { get; set; }
        public Nullable<int> FromMonth { get; set; }
        public Nullable<int> FromYear { get; set; }
        public Nullable<int> ToMonth { get; set; }
        public Nullable<int> ToYear { get; set; }
        public Nullable<bool> CurrentlyWorkingHere { get; set; }
        public Nullable<int> JobLocationID { get; set; }
        public Nullable<int> SalaryID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
    }
}
