//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateEducation
    {
        public int CaEdu_ID { get; set; }
        public Nullable<int> ca_ID { get; set; }
        public string DegreeLevel { get; set; }
        public string MajorSubject { get; set; }
        public string Institute { get; set; }
        public string Grade { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string Description { get; set; }
        public string Activities { get; set; }
        public Nullable<bool> CurrentlyStudyinghere { get; set; }
    }
}
