//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateSkill
    {
        public int CaSkillID { get; set; }
        public Nullable<int> Ca_ID { get; set; }
        public string SkillLevel { get; set; }
        public string Skills { get; set; }
    }
}
