//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateHonour
    {
        public int CaHo_ID { get; set; }
        public Nullable<int> Ca_Id { get; set; }
        public string Title { get; set; }
        public string Associatedwith { get; set; }
        public string Issuer { get; set; }
        public string Issuedon { get; set; }
        public string Description { get; set; }
    }
}
