//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateSearchLocation
    {
        public int csl_Id { get; set; }
        public System.Guid csl_GUID { get; set; }
        public System.DateTime csl_Created { get; set; }
        public int csl_cs_CandidateSearchId { get; set; }
        public int csl_lm_LocationId { get; set; }
        public Nullable<System.DateTime> csl_Deleted { get; set; }
    }
}
