//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateIdealCareerMove
    {
        public int CaICM_ID { get; set; }
        public Nullable<int> Ca_Id { get; set; }
        public Nullable<int> SectorID { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> SalaryFrom { get; set; }
        public Nullable<int> SalaryTo { get; set; }
        public Nullable<int> ExperienceYears { get; set; }
    }
}
