//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateSearchShortlist
    {
        public int css_Id { get; set; }
        public System.Guid css_GUID { get; set; }
        public System.DateTime css_Created { get; set; }
        public System.DateTime css_LastUpdated { get; set; }
        public Nullable<System.DateTime> css_Deleted { get; set; }
        public int css_cs_CandidateSearchId { get; set; }
        public int css_ca_CandidateId { get; set; }
        public int css_lm_RankingId { get; set; }
        public Nullable<System.DateTime> css_CandidateContacted { get; set; }
        public int css_PermissionResult { get; set; }
    }
}
