//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateDocument
    {
        public int cd_Id { get; set; }
        public System.Guid cd_Guid { get; set; }
        public System.DateTime cd_Created { get; set; }
        public int cd_ca_CandidateId { get; set; }
        public int cd_doct_DocumentTypeId { get; set; }
        public string cd_OriginalName { get; set; }
        public string cd_FileExtension { get; set; }
        public string cd_MimeType { get; set; }
        public Nullable<System.DateTime> cd_Deleted { get; set; }
        public string cd_Type { get; set; }
        public Nullable<int> cd_CaEdu_ID { get; set; }
    }
}
