//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateEmployer_T
    {
        public int ID { get; set; }
        public Nullable<int> EmployerID { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DOE { get; set; }
    }
}
