//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidates18oct2018
    {
        public int ca_Id { get; set; }
        public System.Guid ca_GUID { get; set; }
        public System.DateTime ca_Created { get; set; }
        public System.DateTime ca_LastUpdated { get; set; }
        public Nullable<System.DateTime> ca_Deleted { get; set; }
        public int ca_br_OriginatingBrandId { get; set; }
        public string ca_FirstName { get; set; }
        public string ca_Surname { get; set; }
        public string ca_EmailAddress { get; set; }
        public string ca_Password { get; set; }
        public string ca_PhoneMobile { get; set; }
        public string ca_Address1 { get; set; }
        public string ca_Address2 { get; set; }
        public string ca_Address3 { get; set; }
        public string ca_AddressCity { get; set; }
        public string ca_postcode { get; set; }
        public string ca_County { get; set; }
        public Nullable<int> ca_CurrentCountryID { get; set; }
        public int ca_lm_CountryId { get; set; }
        public Nullable<System.DateTime> ca_Terms { get; set; }
        public bool ca_UKResident { get; set; }
        public int ca_Notice { get; set; }
        public int ca_lm_NoticePer { get; set; }
        public int ca_lm_EducationLevel { get; set; }
        public string ca_EducationDetail { get; set; }
        public string ca_Profile { get; set; }
        public bool ca_HasPhoto { get; set; }
        public string ca_PhotoExtension { get; set; }
        public bool ca_ProfileSearchable { get; set; }
        public bool ca_CVSearchable { get; set; }
        public bool ca_DetailsVisible { get; set; }
        public Nullable<int> ca_MediatorKey { get; set; }
        public int ca_st_StatusID { get; set; }
        public string ca_Gender { get; set; }
        public Nullable<System.DateTime> ca_DateOfBirth { get; set; }
        public int ca_ViewCount { get; set; }
        public decimal ca_SalaryFrom { get; set; }
        public decimal ca_SalaryTo { get; set; }
        public int ca_CandidateType { get; set; }
        public int ca_lb_EligibilityId { get; set; }
        public string ca_EducationInstitute { get; set; }
        public Nullable<bool> ca_disabled { get; set; }
        public string ca_disabilityDetails { get; set; }
        public Nullable<decimal> ca_ExpectedSalary { get; set; }
        public string ca_MaritalStatus { get; set; }
        public Nullable<int> ca_FunctionTitleID { get; set; }
        public Nullable<int> ca_CurrentJobTitleID { get; set; }
        public Nullable<int> ca_TotalRelavantExperience { get; set; }
        public Nullable<int> ca_UniversityID { get; set; }
        public Nullable<int> ca_UniCountry { get; set; }
        public Nullable<System.DateTime> ca_LastLogin { get; set; }
        public Nullable<bool> ca_Active { get; set; }
        public Nullable<int> ca_CompletedRegTabs { get; set; }
        public Nullable<bool> ca_IsFresher { get; set; }
        public Nullable<bool> Ca_EmailActivated { get; set; }
        public Nullable<System.DateTime> Ca_EmailActivatedOn { get; set; }
        public Nullable<int> Ca_SectorIndustryID { get; set; }
    }
}
