//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateIdealCareerMove_T
    {
        public int CaICM_ID { get; set; }
        public Nullable<int> Ca_ID { get; set; }
        public Nullable<int> JobTitleID { get; set; }
        public Nullable<int> FunctionID { get; set; }
        public Nullable<int> IndustryID { get; set; }
        public Nullable<int> ExperienceID { get; set; }
        public Nullable<int> ExpectedSalaryID { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
    }
}
