//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateExperience
    {
        public int CaExpID { get; set; }
        public Nullable<int> Ca_ID { get; set; }
        public string JobTitle { get; set; }
        public string Company { get; set; }
        public string TotalExp { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string joblevel { get; set; }
        public string reportingto { get; set; }
        public string industry { get; set; }
        public string fromdate { get; set; }
        public string todate { get; set; }
        public string salary { get; set; }
        public string description { get; set; }
    }
}
