//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateSearch
    {
        public int cs_Id { get; set; }
        public System.Guid cs_GUID { get; set; }
        public System.DateTime cs_Created { get; set; }
        public System.DateTime cs_LastUpdated { get; set; }
        public Nullable<System.DateTime> cs_Deleted { get; set; }
        public int cs_lm_id { get; set; }
        public string cs_SearchName { get; set; }
        public string cs_Keywords { get; set; }
        public int cs_SearchScope { get; set; }
        public bool cs_CbeEnabled { get; set; }
        public int cs_CbeFrequency { get; set; }
        public System.DateTime cs_LastRan { get; set; }
        public int cs_CandidatesInList { get; set; }
        public bool cs_IsCBE { get; set; }
        public bool cs_IsCVOnly { get; set; }
    }
}
