//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyManagement_T
    {
        public int CompanyManagementID { get; set; }
        public Nullable<System.Guid> CM_GUID { get; set; }
        public Nullable<int> Co_ID { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Extn { get; set; }
        public string Name2 { get; set; }
        public string Position2 { get; set; }
        public string Extn2 { get; set; }
        public string Name3 { get; set; }
        public string Position3 { get; set; }
        public string Extn3 { get; set; }
        public string Name4 { get; set; }
        public string Position4 { get; set; }
        public string Extn4 { get; set; }
    }
}
