//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyStatistic
    {
        public int cst_co_CompanyId { get; set; }
        public int cst_lm_id { get; set; }
        public int last24hrs { get; set; }
        public int last48hrs { get; set; }
        public int last168hrs { get; set; }
        public int sumtotal { get; set; }
        public System.DateTime lastupdated { get; set; }
    }
}
