//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class companiesBKP14052019
    {
        public int co_Id { get; set; }
        public System.Guid co_Guid { get; set; }
        public System.DateTime co_Created { get; set; }
        public System.DateTime co_LastUpdated { get; set; }
        public int co_br_HomeBrandId { get; set; }
        public string co_Name { get; set; }
        public string co_RegistrationNumber { get; set; }
        public string co_VatNumber { get; set; }
        public string co_PostalAddress { get; set; }
        public string co_Postcode { get; set; }
        public string co_Telephone { get; set; }
        public bool co_HasLogo { get; set; }
        public string co_LogoExtension { get; set; }
        public Nullable<System.DateTime> co_AcceptedTerms { get; set; }
        public string co_Profile { get; set; }
        public int co_us_SalesRepresentative { get; set; }
        public int co_ClientType { get; set; }
        public string co_CRN { get; set; }
        public int co_ProfileViews { get; set; }
        public int co_st_StatusID { get; set; }
        public decimal co_Funds { get; set; }
        public Nullable<System.DateTime> co_Deleted { get; set; }
        public string co_NameEncoded { get; set; }
        public Nullable<System.DateTime> co_LastAdvert { get; set; }
        public Nullable<bool> co_activated { get; set; }
        public Nullable<bool> co_MasterAc { get; set; }
        public string co_Video { get; set; }
        public Nullable<int> co_CompanySizeID { get; set; }
        public string co_HeaderExtension { get; set; }
        public string co_ProfileTitle1 { get; set; }
        public string co_ProfileTitle2 { get; set; }
        public string co_ProfileTitle3 { get; set; }
        public string co_ProfileTitle4 { get; set; }
        public string co_ProfileTitle5 { get; set; }
        public string co_Profile2 { get; set; }
        public string co_Profile3 { get; set; }
        public string co_Profile4 { get; set; }
        public string co_Profile5 { get; set; }
        public string co_ProfilePicExtn1 { get; set; }
        public string co_ProfilePicExtn2 { get; set; }
        public string co_ProfilePicExtn3 { get; set; }
        public string co_ProfilePicExtn4 { get; set; }
        public string co_ProfilePicExtn5 { get; set; }
        public string co_JobCompanyDesc { get; set; }
        public Nullable<bool> co_ProfilePublished { get; set; }
        public Nullable<bool> co_VideoPublished { get; set; }
        public Nullable<bool> co_GalleryPublished { get; set; }
        public Nullable<bool> co_TestimonialsPublished { get; set; }
        public Nullable<bool> co_MediaPublished { get; set; }
        public string co_CRNo { get; set; }
    }
}
