//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyPackage
    {
        public int cp_Id { get; set; }
        public System.Guid cp_GUID { get; set; }
        public System.DateTime cp_Created { get; set; }
        public System.DateTime cp_LastUpdated { get; set; }
        public int cp_pt_PackageTypeId { get; set; }
        public int cp_co_CompanyId { get; set; }
        public int cp_l_LinkId { get; set; }
        public int cp_Remaining { get; set; }
        public Nullable<System.DateTime> cp_Expires { get; set; }
    }
}
