//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyVideo_T
    {
        public int CoVideo_ID { get; set; }
        public Nullable<int> Co_ID { get; set; }
        public string VideoURL { get; set; }
    }
}
