//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySector
    {
        public int cs_Id { get; set; }
        public System.Guid cs_GUID { get; set; }
        public System.DateTime cs_Created { get; set; }
        public int cs_co_CompanyId { get; set; }
        public int cs_lm_SectorId { get; set; }
    }
}
