//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int comp_Id { get; set; }
        public System.Guid comp_Guid { get; set; }
        public System.DateTime comp_Created { get; set; }
        public int comp_us_Id { get; set; }
        public string comp_Regarding { get; set; }
        public string comp_Details { get; set; }
        public Nullable<System.DateTime> comp_Deleted { get; set; }
    }
}
