//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyTestimonials_T
    {
        public int CTID { get; set; }
        public Nullable<int> Co_ID { get; set; }
        public Nullable<System.Guid> CT_GUID { get; set; }
        public string CTDetails { get; set; }
        public string CTPicExtension { get; set; }
    }
}
