//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ct_Id { get; set; }
        public System.Guid ct_GUID { get; set; }
        public System.DateTime ct_Created { get; set; }
        public System.DateTime ct_LastUpdated { get; set; }
        public int ct_co_CompanyId { get; set; }
        public string ct_Forename { get; set; }
        public string ct_Surname { get; set; }
        public string ct_JobTitle { get; set; }
        public string ct_EmailAddress { get; set; }
        public string ct_Telephone { get; set; }
        public string ct_Password { get; set; }
        public string ct_ApplicationEmail { get; set; }
        public bool ct_Superuser { get; set; }
        public int ct_st_StatusId { get; set; }
        public bool ct_MarketingOptIn { get; set; }
        public Nullable<System.DateTime> ct_Deleted { get; set; }
        public Nullable<System.DateTime> ct_LastLogin { get; set; }
        public Nullable<int> co_PositioninCompanyID { get; set; }
        public Nullable<bool> ct_postjob { get; set; }
        public Nullable<bool> ct_SearchCV { get; set; }
    }
}
