//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentReplace
    {
        public int contr_Id { get; set; }
        public System.Guid contr_Guid { get; set; }
        public string contr_Name { get; set; }
        public string contr_Description { get; set; }
        public int contr_cont_ContentId { get; set; }
    }
}
