//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterAdvSrchSectors_T
    {
        public int ID { get; set; }
        public Nullable<int> co_id { get; set; }
        public Nullable<int> sectorid { get; set; }
        public Nullable<System.DateTime> doe { get; set; }
    }
}
