//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCreditUsage_T
    {
        public int CreditUsageID { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<System.DateTime> UsedOn { get; set; }
        public Nullable<int> CreditTypeID { get; set; }
        public Nullable<int> VacancyID { get; set; }
        public Nullable<int> CandidateID { get; set; }
    }
}
