//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSVouchers_T
    {
        public int VoucherID { get; set; }
        public Nullable<int> SubscriptionID { get; set; }
        public Nullable<int> VoucherMonth { get; set; }
        public Nullable<int> VoucherYear { get; set; }
        public Nullable<int> CreditTypeID { get; set; }
        public Nullable<int> CreditBalance { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
