//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public int eml_id { get; set; }
        public System.Guid eml_guid { get; set; }
        public System.DateTime eml_sent { get; set; }
        public string eml_subject { get; set; }
        public string eml_mailfrom { get; set; }
        public string eml_mailto { get; set; }
        public string eml_mailcc { get; set; }
        public string eml_mailbcc { get; set; }
        public string eml_body { get; set; }
        public string eml_error { get; set; }
        public Nullable<System.DateTime> eml_deleted { get; set; }
    }
}
