//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailContentReplace
    {
        public int emcr_id { get; set; }
        public System.Guid emcr_guid { get; set; }
        public string emcr_name { get; set; }
        public string emcr_description { get; set; }
        public int emcr_emc_emailcontentID { get; set; }
        public Nullable<System.DateTime> emcr_deleted { get; set; }
    }
}
