//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailContent
    {
        public int emc_id { get; set; }
        public System.Guid emc_guid { get; set; }
        public System.DateTime emc_created { get; set; }
        public System.DateTime emc_lastupdated { get; set; }
        public int emc_us_userID { get; set; }
        public string emc_name { get; set; }
        public string emc_subject { get; set; }
        public string emc_mailto { get; set; }
        public string emc_mailfrom { get; set; }
        public string emc_mailcc { get; set; }
        public string emc_mailbcc { get; set; }
        public string emc_body { get; set; }
        public bool emc_plaintextused { get; set; }
        public string emc_plaintext { get; set; }
        public int emc_br_brandid { get; set; }
        public int emc_commonid { get; set; }
        public Nullable<System.DateTime> emc_deleted { get; set; }
    }
}
