//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployerPackages_T
    {
        public int PkgID { get; set; }
        public string Package { get; set; }
        public string Rate { get; set; }
        public string Total { get; set; }
        public string Saving { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Jobs { get; set; }
    }
}
