//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployerActivationCode_Told
    {
        public int ID { get; set; }
        public Nullable<System.Guid> guid { get; set; }
        public Nullable<int> EmployerID { get; set; }
        public string ActivationCodes { get; set; }
        public Nullable<System.DateTime> ActivatedOn { get; set; }
    }
}
