//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public int ent_Id { get; set; }
        public System.Guid ent_Guid { get; set; }
        public System.DateTime ent_Created { get; set; }
        public string ent_Name { get; set; }
    }
}
