//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EY_CVDownloads_T
    {
        public int ID { get; set; }
        public Nullable<int> EmployerID { get; set; }
        public Nullable<int> CandidateID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
