//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeaturedCompany
    {
        public int co_Id { get; set; }
        public string co_Name { get; set; }
        public System.Guid co_Guid { get; set; }
        public Nullable<int> total { get; set; }
    }
}
