//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageResource
    {
        public int id { get; set; }
        public System.DateTime created { get; set; }
        public int createdby { get; set; }
        public System.DateTime lastupdated { get; set; }
        public int lastupdatedby { get; set; }
        public string name { get; set; }
        public string extension { get; set; }
        public int width { get; set; }
        public int height { get; set; }
        public bool library { get; set; }
        public int imageresourcetypeid { get; set; }
    }
}
