//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRoleEquivalence
    {
        public int jre_Id { get; set; }
        public System.Guid jre_Guid { get; set; }
        public System.DateTime jre_Created { get; set; }
        public System.DateTime jre_LastUpdated { get; set; }
        public int jre_br_BranchId { get; set; }
        public int jre_jreg_GroupId { get; set; }
        public int jre_lb_JobRoleId { get; set; }
        public Nullable<System.DateTime> jre_Deleted { get; set; }
    }
}
