//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRoleProfile
    {
        public int jrp_Id { get; set; }
        public System.Guid jrp_Guid { get; set; }
        public System.DateTime jrp_Created { get; set; }
        public System.DateTime jrp_LastUpdated { get; set; }
        public int jrp_us_UserId { get; set; }
        public int jrp_br_BrandId { get; set; }
        public int jrp_lb_JobRoleId { get; set; }
        public bool jrp_DisplayFeature { get; set; }
        public bool jrp_HasPhoto { get; set; }
        public string jrp_PhotoExtension { get; set; }
        public string jrp_FeatureText { get; set; }
        public string jrp_Profile { get; set; }
        public bool jrp_IsTemplate { get; set; }
        public string jrp_TemplateName { get; set; }
        public Nullable<System.DateTime> jrp_Deleted { get; set; }
    }
}
