//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSearchRecruiterType
    {
        public int jsr_Id { get; set; }
        public System.Guid jsr_GUID { get; set; }
        public System.DateTime jsr_Created { get; set; }
        public int jsr_js_JobSearchId { get; set; }
        public int jsr_lm_RecruiterTypeId { get; set; }
        public Nullable<System.DateTime> jsr_Deleted { get; set; }
    }
}
