//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSearchJobType
    {
        public int jsj_Id { get; set; }
        public System.Guid jsj_GUID { get; set; }
        public System.DateTime jsj_Created { get; set; }
        public int jsj_js_JobSearchId { get; set; }
        public int jsj_lm_JobTypeId { get; set; }
        public Nullable<System.DateTime> jsj_Deleted { get; set; }
    }
}
