//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSearchLocation
    {
        public int jsl_Id { get; set; }
        public System.Guid jsl_GUID { get; set; }
        public System.DateTime jsl_Created { get; set; }
        public int jsl_js_JobSearchId { get; set; }
        public int jsl_lm_LocationId { get; set; }
        public Nullable<System.DateTime> jsl_Deleted { get; set; }
    }
}
