//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int lk_Id { get; set; }
        public System.Guid lk_GUID { get; set; }
        public System.DateTime lk_Created { get; set; }
        public System.DateTime lk_LastUpdated { get; set; }
        public Nullable<System.DateTime> lk_Deleted { get; set; }
        public int lk_br_BrandId { get; set; }
        public int lk_lkt_LinkTypeId { get; set; }
        public int lk_lm_LinkId { get; set; }
        public string lk_Parameters { get; set; }
        public string lk_LinkName { get; set; }
        public string lk_URL { get; set; }
        public string lk_H1 { get; set; }
        public string lk_PageTitle { get; set; }
        public string lk_IntroParagraph { get; set; }
        public string lk_MetaKeywords { get; set; }
        public string lk_MetaDescription { get; set; }
        public string lk_Hash { get; set; }
        public int lk_Ordinal { get; set; }
    }
}
