//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListType
    {
        public int lt_Id { get; set; }
        public System.Guid lt_Guid { get; set; }
        public System.DateTime lt_Created { get; set; }
        public string lt_Name { get; set; }
        public bool lt_HasMasterList { get; set; }
        public bool lt_HasBrandList { get; set; }
        public bool lt_IncludeInListAdmin { get; set; }
        public int lt_l_GroupingListId { get; set; }
        public string lt_GroupingLabel { get; set; }
        public bool lt_IsHierarchical { get; set; }
        public string lt_ListLabel { get; set; }
        public bool lt_AllowEdit { get; set; }
        public string lt_EditExceptions { get; set; }
        public bool lt_AllowDelete { get; set; }
        public string lt_DeleteExceptions { get; set; }
    }
}
