//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListsMasterGrouping
    {
        public int lmg_Id { get; set; }
        public System.Guid lmg_Guid { get; set; }
        public System.DateTime lmg_Created { get; set; }
        public int lmg_us_UserId { get; set; }
        public int lmg_lm_GroupId { get; set; }
        public int lmg_lm_GroupMemberId { get; set; }
    }
}
