//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListBrandAssociation
    {
        public int lba_Id { get; set; }
        public System.Guid lba_Guid { get; set; }
        public System.DateTime lba_Created { get; set; }
        public int lba_br_BrandId { get; set; }
        public int lba_lb_BrandListId { get; set; }
        public int lba_lm_MasterListId { get; set; }
    }
}
