//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListsBrandGrouping
    {
        public int lbg_Id { get; set; }
        public System.Guid lbg_Guid { get; set; }
        public System.DateTime lbg_Created { get; set; }
        public int lbg_us_UserId { get; set; }
        public int lbg_lb_GroupId { get; set; }
        public int lbg_lb_GroupMemberId { get; set; }
    }
}
