//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListsMaster
    {
        public int lm_Id { get; set; }
        public System.Guid lm_Guid { get; set; }
        public System.DateTime lm_Created { get; set; }
        public System.DateTime lm_LastUpdated { get; set; }
        public int lm_us_UserId { get; set; }
        public int lm_lt_ListTypeId { get; set; }
        public int lm_lm_ParentId { get; set; }
        public string lm_Value { get; set; }
        public int lm_Ordinal { get; set; }
        public Nullable<short> lm_Ranking { get; set; }
        public Nullable<System.DateTime> lm_Deleted { get; set; }
        public string lm_ValueEncoded { get; set; }
    }
}
