//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListsBrand
    {
        public int lb_Id { get; set; }
        public System.Guid lb_Guid { get; set; }
        public System.DateTime lb_Created { get; set; }
        public System.DateTime lb_LastUpdated { get; set; }
        public int lb_br_BrandId { get; set; }
        public int lb_us_UserId { get; set; }
        public int lb_lt_ListTypeId { get; set; }
        public int lb_lb_ParentId { get; set; }
        public int lb_lm_ImplicitMapping { get; set; }
        public string lb_Value { get; set; }
        public int lb_Ordinal { get; set; }
        public Nullable<System.DateTime> lb_Deleted { get; set; }
    }
}
