//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagementReportGroup
    {
        public int mrepg_Id { get; set; }
        public System.Guid mrepg_Guid { get; set; }
        public System.DateTime mrepg_Created { get; set; }
        public System.DateTime mrepg_LastUpdated { get; set; }
        public int mrepg_us_UserId { get; set; }
        public string mrepg_Name { get; set; }
        public int mrepg_DisplayOrder { get; set; }
    }
}
