//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapping
    {
        public int map_Id { get; set; }
        public System.Guid map_GUID { get; set; }
        public System.DateTime map_Created { get; set; }
        public int map_MapType { get; set; }
        public Nullable<int> map_intIn { get; set; }
        public string map_strIn { get; set; }
        public Nullable<int> map_intOut { get; set; }
        public string map_strOut { get; set; }
    }
}
