//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int id { get; set; }
        public System.DateTime created { get; set; }
        public int createdby { get; set; }
        public string createdbytype { get; set; }
        public System.DateTime lastupdated { get; set; }
        public int lastupdatedby { get; set; }
        public string lastupdatedbytype { get; set; }
        public Nullable<int> parentid { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public int brandid { get; set; }
        public int displayorder { get; set; }
        public int contentid { get; set; }
        public int menuid { get; set; }
        public bool active { get; set; }
        public string usertype { get; set; }
        public bool deleted { get; set; }
    }
}
