//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MicrositeMenuItem
    {
        public int ID { get; set; }
        public int MicrositeID { get; set; }
        public int MicrositeContentID { get; set; }
        public string Title { get; set; }
        public int DisplayOrder { get; set; }
    }
}
