//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Microsite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Microsite()
        {
            this.MicrositeVacancies = new HashSet<MicrositeVacancy>();
        }
    
        public int ID { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int LastUpdatedBy { get; set; }
        public string Name { get; set; }
        public int TemplateID { get; set; }
        public string AppRelativeBaseUrl { get; set; }
        public int HomepageID { get; set; }
        public bool Active { get; set; }
        public string Attributes { get; set; }
        public int ParentSiteID { get; set; }
        public int ClientID { get; set; }
        public int BrandID { get; set; }
        public bool IncludeVacancies { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MicrositeVacancy> MicrositeVacancies { get; set; }
    }
}
