//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MicrositeContent
    {
        public int ID { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int LastUpdatedBy { get; set; }
        public int MicrositeID { get; set; }
        public string Name { get; set; }
        public string PageTitle { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public string HTML { get; set; }
        public bool IsPage { get; set; }
        public string BaseRelativeUrl { get; set; }
    }
}
