//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsArticleBrand
    {
        public int nab_Id { get; set; }
        public System.Guid nab_Guid { get; set; }
        public System.DateTime nab_Created { get; set; }
        public int nab_news_ArticleId { get; set; }
        public int nab_br_BrandId { get; set; }
    }
}
