//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoiseWord
    {
        public int nw_id { get; set; }
        public System.Guid nw_guid { get; set; }
        public string nw_noiseword { get; set; }
        public bool nw_ignoreword { get; set; }
    }
}
