//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int ordl_Id { get; set; }
        public System.Guid ordl_GUID { get; set; }
        public System.DateTime ordl_Created { get; set; }
        public int ordl_ord_OrderId { get; set; }
        public int ordl_Qty { get; set; }
        public int ordl_pp_PackagePriceId { get; set; }
        public int ordl_pt_PackageTypeId { get; set; }
        public double ordl_LineTotal { get; set; }
    }
}
