//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagePrice
    {
        public int pp_Id { get; set; }
        public System.Guid pp_GUID { get; set; }
        public System.DateTime pp_Created { get; set; }
        public System.DateTime pp_LastUpdated { get; set; }
        public int pp_PriceType { get; set; }
        public int pp_l_LinkId { get; set; }
        public int pp_pt_PackageTypeId { get; set; }
        public decimal pp_Price { get; set; }
        public Nullable<System.DateTime> pp_Deleted { get; set; }
    }
}
