//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int pay_Id { get; set; }
        public System.Guid pay_Guid { get; set; }
        public System.DateTime pay_Created { get; set; }
        public int pay_co_CompanyId { get; set; }
        public int pay_ct_ContactId { get; set; }
        public int pay_us_UserId { get; set; }
        public int pay_payt_PayTypeId { get; set; }
        public string pay_Notes { get; set; }
        public decimal pay_Amount { get; set; }
        public int pay_ord_OrderId { get; set; }
        public string pay_pluto { get; set; }
        public decimal pay_VAT { get; set; }
        public decimal pay_AmountNet { get; set; }
        public bool pay_Vatable { get; set; }
        public Nullable<System.DateTime> pay_exported { get; set; }
    }
}
