//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ppaCharge
    {
        public int ppa_Id { get; set; }
        public System.Guid ppa_Guid { get; set; }
        public int ppa_Minimum { get; set; }
        public int ppa_Maximum { get; set; }
        public decimal ppa_CostPerApplication { get; set; }
        public decimal ppa_MinimumMonthlyCharge { get; set; }
    }
}
