//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecommendationJobRole
    {
        public int rjr_Id { get; set; }
        public System.Guid rjr_Guid { get; set; }
        public System.DateTime rjr_Created { get; set; }
        public System.DateTime rjr_LastUpdated { get; set; }
        public int rjr_rec_RecommendationID { get; set; }
        public int rjr_lm_JobRoleId { get; set; }
    }
}
