//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public int rec_Id { get; set; }
        public System.Guid rec_Guid { get; set; }
        public System.DateTime rec_Created { get; set; }
        public System.DateTime rec_LastUpdated { get; set; }
        public int rec_us_UserId { get; set; }
        public string rec_Title { get; set; }
        public Nullable<System.DateTime> rec_DisplayFrom { get; set; }
        public Nullable<System.DateTime> rec_DisplayTo { get; set; }
        public string rec_Summary { get; set; }
        public string rec_URL { get; set; }
        public Nullable<System.DateTime> rec_Deleted { get; set; }
    }
}
