//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int rep_Id { get; set; }
        public System.Guid rep_Guid { get; set; }
        public System.DateTime rep_Created { get; set; }
        public System.DateTime rep_LastUpdated { get; set; }
        public int rep_us_UserId { get; set; }
        public string rep_Name { get; set; }
        public string rep_SQL { get; set; }
        public int rep_st_StatusId { get; set; }
    }
}
