//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportsStandard
    {
        public int reps_Id { get; set; }
        public System.Guid reps_Guid { get; set; }
        public System.DateTime reps_Created { get; set; }
        public System.DateTime reps_LastUpdated { get; set; }
        public string reps_Name { get; set; }
        public Nullable<System.DateTime> reps_Deleted { get; set; }
    }
}
