//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int id { get; set; }
        public System.DateTime created { get; set; }
        public int createdby { get; set; }
        public System.DateTime lastupdated { get; set; }
        public int lastupdatedby { get; set; }
        public bool deleted { get; set; }
        public bool active { get; set; }
        public string title { get; set; }
        public System.DateTime displaydate { get; set; }
        public string summary { get; set; }
        public string body { get; set; }
        public int resourcetypeid { get; set; }
        public string attributesxml { get; set; }
    }
}
