//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryRanx
    {
        public int sr_lv_ListMasterID { get; set; }
        public decimal sr_SalaryMin { get; set; }
        public decimal sr_SalaryMax { get; set; }
    }
}
