//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchScope
    {
        public int ss_Id { get; set; }
        public System.Guid ss_Guid { get; set; }
        public System.DateTime ss_Created { get; set; }
        public int ss_sst_SearchScopeTypeID { get; set; }
        public string ss_Value { get; set; }
    }
}
