//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchScopeType
    {
        public int sst_Id { get; set; }
        public System.Guid sst_Guid { get; set; }
        public System.DateTime sst_Created { get; set; }
        public string sst_Name { get; set; }
    }
}
