//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticType
    {
        public int stt_Id { get; set; }
        public System.Guid stt_GUID { get; set; }
        public System.DateTime stt_Created { get; set; }
        public string stt_Name { get; set; }
    }
}
