//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int st_Id { get; set; }
        public System.Guid st_Guid { get; set; }
        public System.DateTime st_Created { get; set; }
        public string st_Name { get; set; }
        public int st_ent_EntityId { get; set; }
        public bool st_SystemStatus { get; set; }
        public int st_DisplayOrder { get; set; }
    }
}
