//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int st_Id { get; set; }
        public System.Guid st_GUID { get; set; }
        public int st_stt_Type { get; set; }
        public int st_Date { get; set; }
        public int st_Count { get; set; }
        public int st_LinkId { get; set; }
        public string st_ExtraData { get; set; }
    }
}
