//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Synonym
    {
        public int syn_Id { get; set; }
        public System.Guid syn_Guid { get; set; }
        public System.DateTime syn_Created { get; set; }
        public System.DateTime syn_LastUpdated { get; set; }
        public int syn_syng_GroupId { get; set; }
        public string syn_Value { get; set; }
        public Nullable<System.DateTime> syn_Deleted { get; set; }
    }
}
