//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaJ4bFeedMap
    {
        public int TAFeed_ID { get; set; }
        public string j4bSec { get; set; }
        public string TASec { get; set; }
        public string TASectionName { get; set; }
    }
}
