//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int us_Id { get; set; }
        public System.Guid us_Guid { get; set; }
        public System.DateTime us_Created { get; set; }
        public System.DateTime us_LastUpdated { get; set; }
        public Nullable<System.DateTime> us_Deleted { get; set; }
        public int us_lm_TitleId { get; set; }
        public string us_Surname { get; set; }
        public string us_Forename { get; set; }
        public string us_EmailAddress { get; set; }
        public int us_ust_UserTypeId { get; set; }
        public string us_ActiveDirectoryName { get; set; }
        public string us_Password { get; set; }
        public bool us_MaySetCRN { get; set; }
        public bool us_MaySetSalesConsultant { get; set; }
        public bool us_Hidden { get; set; }
        public bool us_Deletable { get; set; }
        public int us_st_StatusId { get; set; }
        public int us_IntegrationKey { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
