//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBrand
    {
        public int uss_Id { get; set; }
        public System.Guid uss_Guid { get; set; }
        public System.DateTime uss_Created { get; set; }
        public int uss_us_UserId { get; set; }
        public int uss_br_BrandId { get; set; }
    }
}
