//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRight
    {
        public int usr_Id { get; set; }
        public System.Guid usr_Guid { get; set; }
        public System.DateTime usr_Created { get; set; }
        public int usr_us_UserId { get; set; }
        public int usr_lm_AreaId { get; set; }
    }
}
