//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacancyShortlistLog
    {
        public int vsl_ID { get; set; }
        public System.DateTime vsl_Created { get; set; }
        public string vsl_SessionID { get; set; }
        public int vsl_ca_CandidateID { get; set; }
        public int vsl_VacancyID { get; set; }
    }
}
