//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacancyLocation
    {
        public int vl_Id { get; set; }
        public System.Guid vl_GUID { get; set; }
        public System.DateTime vl_Created { get; set; }
        public Nullable<System.DateTime> vl_Deleted { get; set; }
        public int vl_vc_VacancyId { get; set; }
        public int vl_lm_LocationId { get; set; }
    }
}
