//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs4Bahrainis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacancyBrand
    {
        public int vb_Id { get; set; }
        public System.Guid vb_GUID { get; set; }
        public System.DateTime vb_Created { get; set; }
        public Nullable<System.DateTime> vb_Deleted { get; set; }
        public int vb_vc_VacancyId { get; set; }
        public int vb_br_BrandId { get; set; }
    }
}
